// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Pixel Pursuit",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Pixel Pursuit",
            targets: ["AppModule"],
            bundleIdentifier: "Ethan-Marshall.Pixel-Pursuit",
            teamIdentifier: "GUDZ7ALN9J",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["./Info.plist", "./README.md"],
            resources: [
                .process("Fonts"),
                .process("Music & Sound Effects"),
                .process("Pixel Pursuit.reality")
            ]
        )
    ]
)
